options(stringsAsFactors=FALSE)
.libPaths(unique(c(Sys.getenv('GSE_REPRO_R_LIB','C:/Users/User/Documents/R/win-library/4.4'),.libPaths())))
suppressPackageStartupMessages({library(ggplot2);library(dplyr);library(tidyr);library(patchwork);library(ggrepel)})
args<-commandArgs(TRUE)
src<-if(length(args))args[1] else 'outputs/reviewer_audit/results'
out<-if(length(args)>1)args[2] else 'outputs/reviewer_audit/delivery'
fig<-file.path(out,'02_Figures');tab<-file.path(out,'03_Tables')
dir.create(fig,recursive=TRUE,showWarnings=FALSE);dir.create(tab,recursive=TRUE,showWarnings=FALSE)
rd<-function(n)read.csv(file.path(src,paste0(n,'.csv')),check.names=FALSE)
wr<-function(x,n)write.csv(x,file.path(tab,paste0(n,'.csv')),row.names=FALSE,na='',fileEncoding='UTF-8')
theme_set(theme_classic(base_size=11,base_family='Arial')+theme(plot.title=element_text(size=13,face='bold'),plot.subtitle=element_text(size=10,color='#444444'),axis.title=element_text(size=11),axis.text=element_text(color='#202020'),legend.title=element_text(size=10),legend.position='bottom',strip.background=element_blank(),strip.text=element_text(face='bold',size=10),plot.margin=margin(8,12,8,8)))
saveplot<-function(p,n,w=8,h=5){ggsave(file.path(fig,paste0(n,'.png')),p,width=w,height=h,dpi=320,bg='white',device=ragg::agg_png);ggsave(file.path(fig,paste0(n,'.pdf')),p,width=w,height=h,device=cairo_pdf,bg='white')}
fmt<-function(q)ifelse(q<.001,formatC(q,format='e',digits=1),formatC(q,format='f',digits=3))
star<-function(q)ifelse(q<.001,'***',ifelse(q<.01,'**',ifelse(q<.05,'*',ifelse(q<.1,'\u2020','ns'))))
canon<-function(n){n<-sub(' - animal$','',n);n}
key<-function(n)gsub('[^a-z0-9]','',tolower(canon(n)))
colors<-c('T-lineage candidate'='#3D5A80','B cell'='#0072B2','Myeloid'='#E69F00','pDC'='#CC79A7','Erythroid'='#D55E00','Cytotoxic T/NK'='#009E73')
u<-rd('annotation_umap');u$reviewed_cell_type<-factor(u$reviewed_cell_type,levels=names(colors))
cent<-u |> group_by(cluster_res0.6) |> summarise(UMAP1=median(UMAP1),UMAP2=median(UMAP2),.groups='drop')
p<-ggplot(u,aes(UMAP1,UMAP2))+geom_point(aes(color=reviewed_cell_type),size=.22,alpha=.65,stroke=0)+geom_label_repel(data=cent,aes(label=cluster_res0.6),size=2.6,fill='white',label.size=.15,seed=4,max.overlaps=50,min.segment.length=0)+scale_color_manual(values=colors,name=NULL,guide=guide_legend(override.aes=list(size=2.5,alpha=1),nrow=2))+coord_equal()+labs(title='Cell lineage annotation',subtitle='13,953 cells; numbers indicate clusters',x='UMAP 1',y='UMAP 2')+theme(axis.text=element_blank(),axis.ticks=element_blank())
saveplot(p,'Fig01A_cell_lineage_UMAP',7.2,5.8)
mk<-rd('annotation_marker_evidence');mk$gene<-factor(mk$gene,levels=unique(mk$gene));mk$cluster<-factor(mk$cluster,levels=rev(0:19));mk$panel<-factor(mk$panel,levels=unique(mk$panel));mk<-mk |> group_by(gene) |> mutate(scaled_expression=as.numeric(scale(mean_log_expression))) |> ungroup()
cl<-rd('annotation_cluster_review');labels<-setNames(paste0(cl$cluster_res0.6,'  ',cl$reviewed_cell_type),cl$cluster_res0.6)
p<-ggplot(mk,aes(gene,cluster))+geom_point(aes(size=pct_expressing,color=scaled_expression))+scale_size_area(max_size=4.8,breaks=c(25,50,75,100),name='Expressing cells (%)')+scale_color_gradientn(colors=c('#DBE5EF','#618DB2','#102C4B'),name='Mean expression\n(gene-scaled)')+facet_grid(~panel,scales='free_x',space='free_x')+scale_y_discrete(labels=labels)+labs(title='Marker evidence by cluster',x=NULL,y=NULL)+theme(axis.text.x=element_text(angle=55,hjust=1,face='italic',size=9),axis.text.y=element_text(size=9),strip.text=element_text(size=9),panel.grid.major.y=element_line(color='#EEEEEE',linewidth=.2))
saveplot(p,'Fig01B_annotation_marker_dotplot',12.5,6.6)
wr(cl,'Table01_cell_annotation_review');wr(rd('annotation_sample_counts'),'Table02_cell_counts_and_QC')
cts<-rd('selection_cell_counts');cts$sample<-factor(paste(cts$patient_pair,ifelse(cts$condition_simple=='diagnosis','Dx','Rel')),levels=c('P1 Dx','P1 Rel','P2 Dx','P2 Rel','P3 Dx','P3 Rel'))
lab<-c(global25='Global top 25%\noriginal definition',within15='Within-sample top 15%\nexploratory core',within25='Within-sample top 25%\nsensitivity',reference95='Reference q95\nabsolute cutoff')
cc<-cts |> filter(analysis%in%c('global25','within15'));cc$definition<-factor(lab[cc$analysis],levels=lab[c('global25','within15')])
p<-ggplot(cc,aes(sample,cells,fill=condition_simple))+geom_col(width=.64)+geom_text(aes(label=cells),vjust=-.35,size=3.3)+facet_wrap(~definition,nrow=1)+scale_fill_manual(values=c(diagnosis='#0072B2',relapse='#D55E00'),labels=c('Diagnosis','Relapse'),name=NULL)+scale_y_continuous(expand=expansion(mult=c(0,.16)))+labs(title='Cells contributing to paired pseudobulk',x=NULL,y='Cells per sample')+theme(axis.text.x=element_text(angle=35,hjust=1))
saveplot(p,'Fig02_paired_sample_cell_counts',8,4.1);wr(cts,'Table03_cell_selection_counts')
sc<-rd('KEGG_within15');original<-rd('KEGG_global25');bulk<-rd('KEGG_bulk')
readable<-function(x)x |> transmute(Pathway=canon(pathway_name),NES=NES,P_value=pval,FDR=padj,Direction=direction,Genes_tested=size,Leading_edge_genes=leadingEdge) |> arrange(FDR)
wr(readable(sc),'Table04_scRNAseq_all_KEGG_within15');wr(readable(bulk),'Table05_bulk_STAT5B_all_KEGG');wr(readable(original),'TableS01_scRNAseq_all_KEGG_global25')
overview<-function(x,title,subtitle,nshow=15){
  z<-x |> filter(padj<.1) |> group_by(direction) |> arrange(padj,.by_group=TRUE) |> slice_head(n=nshow) |> ungroup();z$label<-canon(z$pathway_name);z$label<-factor(z$label,levels=z$label[order(z$NES)])
  cnt<-x |> filter(padj<.1) |> count(direction);note<-paste(paste0(cnt$direction,': ',cnt$n),collapse='; ')
  ggplot(z,aes(NES,label))+geom_vline(xintercept=0,color='#8A8A8A',linewidth=.35)+geom_segment(aes(x=0,xend=NES,yend=label),color='#CCD3DA',linewidth=.6)+geom_point(aes(size=size,color=-log10(padj)),alpha=1)+scale_color_gradient(low='#7099B5',high='#4C075F',name=expression(-log[10](FDR)))+scale_size_continuous(range=c(2,5),name='Genes tested')+labs(title=title,subtitle=paste0(subtitle,'\n',note,' at FDR < 0.10; up to ',nshow,' per direction, ranked by FDR'),x='Normalized enrichment score (NES)',y=NULL)+theme(axis.text.y=element_text(size=9))
}
saveplot(overview(sc,'Relapse scRNA-seq: KEGG enrichment','Within-sample top 15%; paired relapse vs diagnosis'),'Fig03_scRNAseq_all_pathway_overview',9.5,7.8)
saveplot(overview(bulk,'STAT5B N642H bulk RNA-seq: KEGG enrichment','N642H vs control; independent 3 vs 3 samples'),'Fig04_bulk_all_pathway_overview',9.5,8.4)
saveplot(overview(original,'Relapse scRNA-seq: original definition','Global top 25%; paired relapse vs diagnosis'),'FigS01_original_scRNAseq_overview',9.5,7.8)
saveplot(overview(sc,'Relapse scRNA-seq','Within-sample top 15%; paired comparison',8)+theme(axis.text.y=element_text(size=11)),'Fig03B_scRNAseq_slide_overview',11,6)
saveplot(overview(bulk,'STAT5B N642H bulk RNA-seq','N642H vs control; independent 3 vs 3',8)+theme(axis.text.y=element_text(size=11)),'Fig04B_bulk_slide_overview',11,6)
cross<-function(x,id){a<-x |> transmute(key=key(pathway_name),Pathway=canon(pathway_name),sc_NES=NES,sc_FDR=padj,sc_P=pval,sc_genes=size);b<-bulk |> transmute(key=key(pathway_name),bulk_Pathway=canon(pathway_name),bulk_NES=NES,bulk_FDR=padj,bulk_P=pval,bulk_genes=size);stopifnot(!anyDuplicated(a$key),!anyDuplicated(b$key));full_join(a,b,by='key') |> mutate(Pathway=coalesce(Pathway,bulk_Pathway),analysis=id,tested_in_both=!is.na(sc_FDR)&!is.na(bulk_FDR),sc_significant=!is.na(sc_FDR)&sc_FDR<.1,bulk_significant=!is.na(bulk_FDR)&bulk_FDR<.1,same_direction=tested_in_both & sign(sc_NES)==sign(bulk_NES),shared_FDR010=sc_significant&bulk_significant&same_direction) |> select(-bulk_Pathway) }
cx<-bind_rows(cross(sc,'within15'),cross(original,'global25'));wr(cx,'Table06_cross_dataset_pathway_membership');wr(cx |> filter(shared_FDR010) |> arrange(analysis,pmax(sc_FDR,bulk_FDR)),'Table07_same_direction_intersection')
venn<-function(x,id,dir){
  z<-x |> filter(analysis==id,tested_in_both);a<-z$key[z$sc_significant & if(dir=='Up')z$sc_NES>0 else z$sc_NES<0];b<-z$key[z$bulk_significant & if(dir=='Up')z$bulk_NES>0 else z$bulk_NES<0]
  theta<-seq(0,2*pi,length.out=301);cir<-bind_rows(data.frame(x=.85+cos(theta),y=sin(theta),Dataset='scRNA-seq'),data.frame(x=2.05+cos(theta),y=sin(theta),Dataset='Bulk'))
  txt<-data.frame(x=c(.4,1.45,2.5),y=0,label=c(length(setdiff(a,b)),length(intersect(a,b)),length(setdiff(b,a))))
  ggplot(cir,aes(x,y,group=Dataset))+geom_polygon(aes(fill=Dataset),alpha=.18,color=NA)+geom_path(aes(color=Dataset),linewidth=.65)+geom_text(data=txt,aes(x,y,label=label),inherit.aes=FALSE,size=5.5,fontface='bold')+annotate('text',x=c(.55,2.4),y=1.25,label=c('scRNA-seq','Bulk'),size=3.6,color=c('#0072B2','#D55E00'))+scale_fill_manual(values=c('scRNA-seq'='#0072B2',Bulk='#D55E00'))+scale_color_manual(values=c('scRNA-seq'='#0072B2',Bulk='#D55E00'))+coord_equal(xlim=c(-.3,3.25),ylim=c(-1.2,1.55))+theme_void(base_family='Arial')+theme(legend.position='none',plot.title=element_text(size=12,face='bold',hjust=.5),plot.subtitle=element_text(size=9,hjust=.5))+labs(title=paste0(dir,'-enriched'),subtitle=paste0(nrow(z),' common tested pathways'))
}
p<-(venn(cx,'within15','Up')+venn(cx,'within15','Down')) / (venn(cx,'global25','Up')+venn(cx,'global25','Down'))+plot_annotation(title='Direction-matched KEGG overlap',subtitle='Top row: within-sample top 15% (exploratory); bottom row: original global top 25%\nFDR < 0.10 in each full collection; circles are not proportional to set size',tag_levels='A')
saveplot(p,'Fig05_direction_matched_intersection',9,7.6)
shared<-cx |> filter(analysis=='within15',shared_FDR010) |> arrange(desc(pmin(sc_NES,bulk_NES)))
z<-bind_rows(shared |> transmute(Pathway,Dataset='Relapse\nscRNA-seq',NES=sc_NES,FDR=sc_FDR),shared |> transmute(Pathway,Dataset='STAT5B N642H\nbulk RNA-seq',NES=bulk_NES,FDR=bulk_FDR));z$Pathway<-factor(z$Pathway,levels=rev(shared$Pathway));z$Dataset<-factor(z$Dataset,levels=c('Relapse\nscRNA-seq','STAT5B N642H\nbulk RNA-seq'))
p<-ggplot(z,aes(Dataset,Pathway,fill=NES))+geom_tile(color='white',linewidth=.7)+geom_text(aes(label=paste0(sprintf('%.2f',NES),' ',star(FDR))),size=3.2)+scale_fill_gradient2(low='#2166AC',mid='white',high='#B2182B',midpoint=0,limits=c(-3,3),oob=scales::squish,name='NES')+labs(title='Shared KEGG pathways',subtitle='Within-sample top 15%; both datasets FDR < 0.10',x=NULL,y=NULL,caption='* FDR < 0.05; ** < 0.01; *** < 0.001; \u2020 < 0.10\nPathway names do not imply the corresponding disease is present.')+theme(axis.line=element_blank(),axis.ticks=element_blank(),axis.text.y=element_text(size=9),plot.caption=element_text(hjust=0,size=9))
saveplot(p,'Fig06_shared_pathways_NES_heatmap',8,max(5,.24*nrow(shared)+2.1))
topshared<-shared |> arrange(pmax(sc_FDR,bulk_FDR)) |> slice_head(n=15)
zp<-z |> filter(as.character(Pathway)%in%topshared$Pathway);zp$Pathway<-factor(as.character(zp$Pathway),levels=rev(topshared$Pathway))
ps<-p %+% zp;ps<-ps+labs(title='Shared pathways: strongest joint evidence',subtitle='Up to 15 pathways, ranked by the larger FDR across datasets')+theme(axis.text.y=element_text(size=11))
saveplot(ps,'Fig06B_shared_strongest',11,6)
targets<-c('Proteasome','Mitophagy','Autophagy','Autophagy - other','Oxidative phosphorylation','Ribosome')
targ<-bind_rows(original |> mutate(Dataset='scRNA-seq\nglobal top 25%'),sc |> mutate(Dataset='scRNA-seq\nwithin-sample top 15%'),bulk |> mutate(Dataset='STAT5B N642H\nbulk RNA-seq')) |> mutate(Pathway=canon(pathway_name)) |> filter(Pathway%in%targets)
targ$Pathway<-factor(targ$Pathway,levels=rev(targets));targ$Dataset<-factor(targ$Dataset,levels=c('scRNA-seq\nglobal top 25%','scRNA-seq\nwithin-sample top 15%','STAT5B N642H\nbulk RNA-seq'))
p<-ggplot(targ,aes(NES,Pathway))+geom_vline(xintercept=0,color='#AAAAAA',linewidth=.35)+geom_segment(aes(x=0,xend=NES,yend=Pathway),color='#B7C7D2',linewidth=.6)+geom_point(aes(fill=padj<.05),shape=21,size=2.7,color='#1C4B65',stroke=.7)+geom_text(aes(label=paste0('q=',fmt(padj),' ',star(padj))),nudge_x=.12,hjust=0,size=2.9)+facet_wrap(~Dataset,nrow=1)+scale_fill_manual(values=c('FALSE'='white','TRUE'='#1C4B65'),guide='none')+scale_x_continuous(limits=c(min(0,min(targ$NES)-.3),max(targ$NES)+1.25),breaks=0:3)+labs(title='Target pathways across analysis definitions',subtitle='Positive NES: higher in relapse or STAT5B N642H; q = whole-collection BH FDR',x='NES',y=NULL,caption='* q < 0.05; ** < 0.01; *** < 0.001; \u2020 < 0.10; ns \u2265 0.10. Blank: not tested in that catalog.')+theme(axis.text.y=element_text(size=10),plot.caption=element_text(hjust=0,size=9))
saveplot(p,'Fig07_target_pathway_audit',11,4.8);wr(targ |> select(Dataset,Pathway,NES,pval,padj,size,leadingEdge),'Table08_target_pathway_FDR')
pair<-rd('target_paired_direction') |> filter(analysis=='within15',pathway%in%c('Proteasome','Mitophagy - animal'));pair$pathway<-canon(pair$pathway)
pp<-pair |> pivot_longer(c(diagnosis,relapse),names_to='condition',values_to='score');pp$condition<-factor(pp$condition,levels=c('diagnosis','relapse'))
p<-ggplot(pp,aes(condition,score,group=patient_pair,color=patient_pair,shape=patient_pair))+geom_line(linewidth=.65)+geom_point(size=2.6)+facet_wrap(~pathway,scales='free_y')+scale_color_manual(values=c(P1='#0072B2',P2='#D55E00',P3='#009E73'),name='Patient')+scale_shape_manual(values=c(P1=16,P2=17,P3=15),name='Patient')+scale_x_discrete(labels=c('Diagnosis','Relapse'))+labs(title='Within-patient pathway direction',subtitle='Within-sample top 15%; GSEA leading-edge genes',x=NULL,y='Mean log2 CPM',caption='Descriptive check of genes selected from the same GSEA. This is not an independent validation test.')+theme(plot.caption=element_text(hjust=0,size=9))
saveplot(p,'Fig08_paired_leading_edge_direction',7.5,4.4);wr(rd('target_paired_direction'),'Table09_paired_direction_descriptive')
sen<-bind_rows(rd('KEGG_target_summary'),rd('KEGG_within15_symbol_sensitivity') |> filter(pathway_id%in%c('hsa03050','hsa04137','hsa04140','hsa04136'))) |> mutate(Pathway=canon(pathway_name))
wr(sen |> select(analysis,Pathway,NES,pval,padj,size),'TableS02_definition_and_gene_symbol_sensitivity')
cnt<-bind_rows(sc |> mutate(Dataset='scRNAseq_within15'),original |> mutate(Dataset='scRNAseq_global25'),bulk |> mutate(Dataset='bulk_STAT5B')) |> group_by(Dataset) |> summarise(tested_pathways=n(),up_FDR005=sum(padj<.05 & NES>0),down_FDR005=sum(padj<.05 & NES<0),up_FDR010=sum(padj<.1 & NES>0),down_FDR010=sum(padj<.1 & NES<0),.groups='drop');wr(cnt,'Table10_enrichment_counts')
dir.create(file.path(out,'04_Code_Availability'),recursive=TRUE,showWarnings=FALSE)
jsonlite::write_json(list(counts=cnt,targets=as.data.frame(targ |> select(Dataset,Pathway,NES,padj)),intersection=as.data.frame(cx |> group_by(analysis) |> summarise(common_tested=sum(tested_in_both),shared_up=sum(shared_FDR010 & sc_NES>0,na.rm=TRUE),shared_down=sum(shared_FDR010 & sc_NES<0,na.rm=TRUE))),reviewed=Sys.Date()),file.path(out,'04_Code_Availability','summary_for_slides.json'),pretty=TRUE,auto_unbox=TRUE)
cat('Figures and reader-facing tables complete\n');print(cnt)
